### PR TITLE
made main blogpost mockup

### PR DESCRIPTION
**Pull request by ericz82**

### CODE REVIEW

**Comment by ajaska** [comment]
@ericz82 pls respond

**Comment by ajaska** [comment]
oh also can we move it to sub-directories like html/ and css/

thank

**Comment by ericz82** [comment]
@ajaska Whoops sorry! Yeah, I'll just change the name, add sub-directories and make another push?

**Comment by ericz82** [comment]
oh wait, I need to rename the .html file

**Comment by ajaska** [comment]
Hm probably want to update the html to use the renamed files too

**Comment by ericz82** [comment]
@ajaska goddamn @_@

**Pull request merged**
