### PR TITLE
Add a styleguide stylesheet and setup SASS

### PR DESCRIPTION
**Pull request by mngyuan**
this PR adds a couple quick new techs to our repo which will likely replace when we package them in with mern, and creates some TODOs for everyone:
- convert your stylesheets to SASS (probably just change the extension)
- add `@import 'common';` to the top
- update your html to look for `../css/compiled/filename.css` instead of `../css/filename.css`

(or i could just do that in this PR if y'all want)

also we should talk about default fonts because the styleguide uses Lato and Montserrat
## gulp

The no-longer latest and greatest JS task runner, where you write your build tasks as javascript functions instead of configs. We only have 2 build tasks: compile our Sass, and serve the files on localhost. For now, all this means is you run `gulp` while developing instead of `python -m SimpleHTTPServer` or whatever you've been doing.
## SASS

A CSS preprocessor with support for variables, nested styles, etc. The docs are really good: http://sass-lang.com/guide
Some notes:
- `_filename.scss` files are partials, which can't be used as standalone stylesheets but can be used with `@import 'filename';` statements. `_common.scss` and `_styleguide.scss` are example usages
- you can multiply units (and you should! try `2 * $base-unit`)

### CODE REVIEW

**Comment by mngyuan** [comment]
also i went and deleted all the trailing whitespaces in the html because my editor is set up to do that

**Comment by ajaska** [comment]
Oh, looks like you committed the `node_modules` directory. I wouldn't recommend that ... instead make a package.json and add dependencies

**Comment by mngyuan** [comment]
oh, didn't know node updated their recommendation on committing node_modules. i've removed it :)

**Comment by ajaska** [comment]
Might conflict with #11  and #12 but yolo, looks good to me

**Pull request merged**
