### PR TITLE
blog posts + sidebar on mainpage

### PR DESCRIPTION
**Pull request by jpdstan**
some good shit right her

### CODE REVIEW

**Comment by ajaska** [comment]
Looks dope, can you just update a few things so it can render without a webserver for now?

``` diff
diff --git a/html/blog.html b/html/blog.html
index 92e4d30..fba38e7 100644
--- a/html/blog.html
+++ b/html/blog.html
@@ -3,7 +3,7 @@
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
-               <link href="/css/blog.css" rel="stylesheet">
+               <link href="../css/blog.css" rel="stylesheet">
                <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        </head>
        <title>FAST Blog</title>
@@ -11,14 +11,14 @@
                <div class="container pure-g">
                        <div class="blog-container pure-u-5-6">
                                <div class="blog-post-container">
-                                       <img class="blog-image" src="/img/cat.jpg" />
+                                       <img class="blog-image" src="../img/cat.jpg" />
                                        <h1 class="blog-title">Countdown to X</h1>
                                        <h3 class="blog-description">March 16th 2014</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse</p>
                                        <a class="pure-button" href="#">read more</a>
                                </div>
                                <div class="blog-post-container">
-                                       <img class="blog-image" src="/img/teddy.jpg" />
+                                       <img class="blog-image" src="../img/teddy.jpg" />
                                        <h1 class="blog-title">Post-traumatic Spring Break Disorder</h1>
                                        <h3 class="blog-description">March 16th 2014</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse</p>
@@ -32,7 +32,7 @@
                                <iframe src="http://snapwidget.com/in/?u=ZmFzdGNhbHxpbnwxMjV8M3wzfHxub3w1fG5vbmV8b25TdGFydHx5ZXN8bm8=&ve=090316" title="Instagram Widget" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:250px; height:390px"></iframe>

                                <h2>Twitter</h2>
-                               <a class="twitter-grid" href="https://twitter.com/TwitterDev/timelines/539487832448843776">National Park Tweets</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
+                               <a class="twitter-grid" href="https://twitter.com/TwitterDev/timelines/539487832448843776">National Park Tweets</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                        </div>
                </div>
        </body>
```

**Comment by jpdstan** [comment]
wait what do you mean? i can open the html just fine on a browser

**Comment by ajaska** [comment]
the non-relative links are making it look in weird places.

and the `//` on the twitter link makes it look at `file://...`

**Comment by jpdstan** [comment]
ohhh is that what u fixed? kk got it thnx

**Pull request merged**
